let tryReferenceError = () => {
//     function ab() { };
//     try {
//         ab();
//     } catch (e) {
//         console.log("Error : " + e.name);
//     }
// }